### 1. 데이터 과학, 파이썬 소개

- 1.6 파이썬 실습

In [1]:
# friend 객체에 값을 할당하기

friend=1
type(friend)

int

In [2]:
# 연산을 이용해 원과 삼각형의 넓이 구하기

r=2
circle_area=3.14 * (r**2)
x=3
y=4
triangle_area=x*y/2
print(circle_area, triangle_area)

12.56 6.0


In [4]:
# 문자열 계산하기
print('py'+'thon')
print('py' 'thon')
print('py'*3)

python
python
pypypy


In [5]:
# 0부터 시작할 위치 지정해 값 추가

clr_names=['red','green','gold','blue']

clr_names.insert(1,'black')

clr_names

['red', 'black', 'green', 'gold', 'blue']

---

In [6]:
# 튜플 만들기
t=(1,2,3)
type(t)

tuple

In [7]:
a,b=1,2

In [8]:
print((a,b))

(1, 2)


In [13]:
# in 연산자를 이용해 값 확인

a=set((1,2,3))
a

{1, 2, 3}

In [10]:
1 in a

True

In [11]:
c=tuple(a)
type(c)

tuple

In [12]:
c

(1, 2, 3)

In [14]:
3 in c

True

---

In [15]:
# 딕셔너리 만들기

d=dict(a=1, b=3, c=5)
type(d)

dict

In [16]:
clr_names={'apple':'red', 'banana':'yellow'}
clr_names

{'apple': 'red', 'banana': 'yellow'}

In [17]:
clr_names['apple']

'red'

In [18]:
clr_names[0]

KeyError: 0

In [20]:
clr_names['cherry']='red'
clr_names

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}

---

In [21]:
# numpy 사용해보기

import numpy as np

In [22]:
a=np.array([0,1,2,3,4,5])
a.ndim # 차원

1

In [23]:
a.shape

(6,)

In [24]:
a.dtype

dtype('int32')

In [25]:
a[ [2,3,4] ]

array([2, 3, 4])

In [26]:
a>4

array([False, False, False, False, False,  True])

In [27]:
a[a>4]

array([5])

---

In [28]:
# 배열의 기본 활용 연습하기

x=[0.0, 1, 2, 3, 4]
y=np.array(x)
y

array([0., 1., 2., 3., 4.])

In [29]:
y=np.array([
    [0.0,1,2,3,4],
    [5,6,7,8,9]
])
y

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [30]:
y.shape

(2, 5)

In [31]:
y=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
y.shape

(2, 2, 2)

In [32]:
a=np.array([
    [1,2],
    [3,4],
    [5,6]
], float)

a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [33]:
a.shape

(3, 2)

In [34]:
arr=np.arange(10, dtype=float).reshape((2,5))
arr

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [35]:
arr[0]

array([0., 1., 2., 3., 4.])

In [36]:
arr[0,3]

3.0

In [37]:
arr[0][3]

3.0

In [38]:
arr[0,:]

array([0., 1., 2., 3., 4.])

In [39]:
arr[:,0]

array([0., 5.])

---

- 판다스의 시리즈와 데이터프레임을 임포트하기

In [40]:
from pandas import Series, DataFrame

s=Series([0.1, 1.2, 2.3, 3.4, 4.5], index=['a', 'b', 'c', 'd', 'e'])

In [41]:
s['a']

0.1

In [42]:
s[ ['a','c'] ]

a    0.1
c    2.3
dtype: float64

In [43]:
s[ [0,2] ]

a    0.1
c    2.3
dtype: float64

In [44]:
s[s>2]

c    2.3
d    3.4
e    4.5
dtype: float64

In [45]:
s1=Series({'a': 0.1, 'b':1.2, 'c':2.3})
s2=Series({'a': 1.0, 'b':2.0, 'c':3.0})

In [46]:
s1+s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [47]:
s1=Series(np.arange(10.0, 20.0))
s1.describe()

count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [48]:
s1

0    10.0
1    11.0
2    12.0
3    13.0
4    14.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64

In [49]:
summ=s1.describe()
summ['mean']

14.5

In [50]:
s1=Series(np.arange(1.0, 6), index=['a','a','b','c','d'])

In [51]:
s1

a    1.0
a    2.0
b    3.0
c    4.0
d    5.0
dtype: float64

In [53]:
s1.drop('a', inplace=True)
s1

b    3.0
c    4.0
d    5.0
dtype: float64

---

- 데이터프레임 다양하게 생성해보기

In [54]:
from pandas import Series, DataFrame

In [55]:
raw_data={'co10':[1,2,3,4],
         'col1':[10,20,30,40],
         'col2':[100,200,300,400]}

data=DataFrame(raw_data)
print(data)

   co10  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400


In [56]:
a=np.array([
    [1.0, 2],
    [3,4]
])

In [57]:
a

array([[1., 2.],
       [3., 4.]])

In [58]:
df=DataFrame(a, columns=['dogs','cats'], index=['Alice','Bob'])
df

dogs  cats
Alice   1.0   2.0
Bob     3.0   4.0

---

In [60]:
import pandas as pd

df.to_csv('202207211536.csv',sep='\t', encoding='utf-8')
writer=pd.ExcelWriter('202207211536.xlsx')
df.to_excel(writer, 'DataFrame')
writer.save()