- 2.6 행렬의 분해: 고윳값, 고유 벡터, 대각화

- - 1. 분석모형 응용-주성분 분석

In [3]:
import numpy as np

from sklearn.decomposition import PCA

M=np.array([
    [-1,-1,-1],
    [-2,-1,2],
    [-3,-2,0],
    [1,1,2],
    [2,1,1],
    [3,2,4],
    [2,0,3],
    [3,5,1],
    [4,2,3],
    [3,3,2]
])

pca=PCA(n_components=2)

pca.fit(M)

PCA(n_components=2)

In [6]:
PC=pca.transform(M)

In [7]:
s, V=np.linalg.eig(pca.get_covariance())
V.T.dot(M.T).T

array([[-1.63789386,  0.38309423, -0.41296792],
       [-1.50265209, -1.67967793,  1.98008049],
       [-3.43143719, -0.83088857,  0.73134327],
       [ 1.9287851 , -0.84878936,  1.24873722],
       [ 2.3753258 ,  0.28259255,  0.52722744],
       [ 4.59500215, -1.03189193,  2.61173397],
       [ 2.3475376 , -0.06571181,  2.73582697],
       [ 5.55104049, -1.38406422, -1.5067567 ],
       [ 5.04154285,  0.09948998,  1.89022418],
       [ 4.62279035, -0.68358757,  0.40313444]])

---

- 2.7 파이썬 실습

- - numpy, scipy 이용한 선형대수 연산

In [8]:
import numpy as np
from scipy import linalg, sparse

In [9]:
A=np.matrix(np.random.random((2,2)))
A

matrix([[0.81972744, 0.50570645],
        [0.09569674, 0.65448248]])

In [16]:
A.I

matrix([[ 1.34087018, -1.03606547],
        [-0.19605858,  1.6794156 ]])

In [17]:
linalg.det(A)

0.4881027914850743

In [18]:
np.add(A,D)

matrix([[3.81972744, 4.50570645],
        [5.09569674, 6.65448248]])

In [20]:
np.subtract(A,D)

matrix([[-2.18027256, -3.49429355],
        [-4.90430326, -5.34551752]])

In [21]:
np.divide(A,D)

matrix([[0.27324248, 0.12642661],
        [0.01913935, 0.10908041]])

In [11]:
b=np.random.random((2,2))
b

array([[0.06294109, 0.5834834 ],
       [0.4432309 , 0.19369632]])

In [12]:
B=np.asmatrix(b)
B

matrix([[0.06294109, 0.5834834 ],
        [0.4432309 , 0.19369632]])

In [13]:
C=np.mat(np.random.random((10,5)))
C

matrix([[0.07459771, 0.86374324, 0.14579294, 0.86444324, 0.10698049],
        [0.1296549 , 0.99856142, 0.22848926, 0.49303185, 0.21886579],
        [0.46055497, 0.1638369 , 0.65749323, 0.41606771, 0.50198762],
        [0.23627547, 0.72604286, 0.11209106, 0.05702516, 0.56507831],
        [0.41471693, 0.53455984, 0.41471198, 0.15593426, 0.2792943 ],
        [0.11732191, 0.74639128, 0.81926944, 0.89530128, 0.46436903],
        [0.83227621, 0.32045459, 0.71272557, 0.45806958, 0.16484764],
        [0.62435179, 0.83273177, 0.17202085, 0.89416061, 0.72817806],
        [0.12679558, 0.24640226, 0.91360728, 0.13777316, 0.15683967],
        [0.86008003, 0.13702304, 0.3011031 , 0.04253708, 0.51748386]])

In [15]:
D=np.mat([
    [3,4],
    [5,6]
])
D

matrix([[3, 4],
        [5, 6]])

In [23]:
print(D@B) # DxB

[[1.96174686 2.52523547]
 [2.97409084 4.07959491]]


In [24]:
print(np.dot(D,B)) # DxB

[[1.96174686 2.52523547]
 [2.97409084 4.07959491]]


In [25]:
print(np.multiply(D,B)) # 행렬곱이 아니라 단순히 대응 원소끼리 곱

[[0.18882326 2.33393361]
 [2.2161545  1.16217789]]


In [26]:
G=np.mat(np.identity(2)) # 항등
G

matrix([[1., 0.],
        [0., 1.]])

---

- - 행렬 A의 고윳값, 고유 벡터 구하기

In [29]:
linalg.eigvals(A) # 고윳값

array([0.97209631+0.j, 0.50211362+0.j])

In [31]:
la, v=linalg.eig(A) # 고유 벡터

In [32]:
l1, l2= la # 고윳값 to l1, l2

In [33]:
l1

(0.9720963062066519+0j)

In [34]:
l2 # 고윳값(방향)

(0.5021136160775737+0j)

In [35]:
v[:,0] # 고유 벡터(크기)

array([0.95748327, 0.28848878])

In [36]:
v[:,1]

array([-0.84683175,  0.53186087])

- - 3. 희소행렬 만들고 확인하기

In [37]:
C

matrix([[0.07459771, 0.86374324, 0.14579294, 0.86444324, 0.10698049],
        [0.1296549 , 0.99856142, 0.22848926, 0.49303185, 0.21886579],
        [0.46055497, 0.1638369 , 0.65749323, 0.41606771, 0.50198762],
        [0.23627547, 0.72604286, 0.11209106, 0.05702516, 0.56507831],
        [0.41471693, 0.53455984, 0.41471198, 0.15593426, 0.2792943 ],
        [0.11732191, 0.74639128, 0.81926944, 0.89530128, 0.46436903],
        [0.83227621, 0.32045459, 0.71272557, 0.45806958, 0.16484764],
        [0.62435179, 0.83273177, 0.17202085, 0.89416061, 0.72817806],
        [0.12679558, 0.24640226, 0.91360728, 0.13777316, 0.15683967],
        [0.86008003, 0.13702304, 0.3011031 , 0.04253708, 0.51748386]])

In [38]:
C[C>0.5]=0

In [39]:
C

matrix([[0.07459771, 0.        , 0.14579294, 0.        , 0.10698049],
        [0.1296549 , 0.        , 0.22848926, 0.49303185, 0.21886579],
        [0.46055497, 0.1638369 , 0.        , 0.41606771, 0.        ],
        [0.23627547, 0.        , 0.11209106, 0.05702516, 0.        ],
        [0.41471693, 0.        , 0.41471198, 0.15593426, 0.2792943 ],
        [0.11732191, 0.        , 0.        , 0.        , 0.46436903],
        [0.        , 0.32045459, 0.        , 0.45806958, 0.16484764],
        [0.        , 0.        , 0.17202085, 0.        , 0.        ],
        [0.12679558, 0.24640226, 0.        , 0.13777316, 0.15683967],
        [0.        , 0.13702304, 0.3011031 , 0.04253708, 0.        ]])

In [40]:
H=sparse.csr_matrix(C) # 희소행렬 변환

In [41]:
H

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 30 stored elements in Compressed Sparse Row format>

In [43]:
H.todense() # dense matrix.. 일반 행렬로 변환

matrix([[0.07459771, 0.        , 0.14579294, 0.        , 0.10698049],
        [0.1296549 , 0.        , 0.22848926, 0.49303185, 0.21886579],
        [0.46055497, 0.1638369 , 0.        , 0.41606771, 0.        ],
        [0.23627547, 0.        , 0.11209106, 0.05702516, 0.        ],
        [0.41471693, 0.        , 0.41471198, 0.15593426, 0.2792943 ],
        [0.11732191, 0.        , 0.        , 0.        , 0.46436903],
        [0.        , 0.32045459, 0.        , 0.45806958, 0.16484764],
        [0.        , 0.        , 0.17202085, 0.        , 0.        ],
        [0.12679558, 0.24640226, 0.        , 0.13777316, 0.15683967],
        [0.        , 0.13702304, 0.3011031 , 0.04253708, 0.        ]])

In [44]:
sparse.isspmatrix_csr(H)

True